name: Testing and Linting

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - "**.md"
      - "docker/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - "**.md"
      - "docker/**"
  workflow_dispatch: # allow triggering workflow manually
    inputs:
      reason:
        description: "Reason for Running"
        required: false
        default: "Manually trigger ci"


jobs:
  run-ci:
    uses: TAI-src/workflows/.github/workflows/ci.yml@main
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository and create PR
      contents: write
      pull-requests: write
    with:
      docker-service: ttex
      lint-src: ttex
    secrets: inherit

